project:
  type: website

website:
  title: "today"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd

format:
  html:
    theme: cosmo
    toc: true

#jupyter: python312_2024
